"""empty message

Revision ID: 229d56e7bacf
Revises: 39b14d49b966
Create Date: 2026-06-12 21:35:58.194831

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "229d56e7bacf"
down_revision: str | Sequence[str] | None = "39b14d49b966"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipe", "image_url", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipe", "image_url", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
