"""empty message

Revision ID: 7983a09a44a6
Revises:
Create Date: 2026-06-07 15:39:47.454868

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7983a09a44a6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
